spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/filterpackmate_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: filterpackmate-backend